### ISSUE TITLE
Your repo was duplicated?

### ISSUE THREAD

**Issue by TonSilver** [FJust/SwiftyMD5#1]
Repo: https://github.com/ChaosTong/StringMD5

**Comment by JustLee-me** [comment]
Maybe ，this repo that I'm copy from Kingfisher🤔

Sent from my iPhone

On 5 Oct 2017, at 22:36, Anton Serebryakov <notifications@github.com<mailto:notifications@github.com>> wrote:


Repo: https://github.com/ChaosTong/StringMD5

**Comment by TonSilver** [comment]
Thanx!
